// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/dex/pair": {
            "get": {
                "description": "Get information about DEX pairs (supports comma-separated addresses)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dex"
                ],
                "summary": "Get Dex Pair Info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract Addresses (comma-separated)",
                        "name": "contract_address",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Network Slug",
                        "name": "network_slug",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Network ID",
                        "name": "network_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.DexPairInfo"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/nft/floor_price": {
            "get": {
                "description": "Get floor price of NFT collections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nft"
                ],
                "summary": "Get NFT Floor Price",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Collection Slugs (comma separated)",
                        "name": "slugs",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Convert to USD",
                        "name": "convert_to_usd",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.NFTFloorPriceInfo"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/token/price": {
            "get": {
                "description": "Get price of tokens by IDs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "Get Token Price",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token IDs (comma separated)",
                        "name": "ids",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/utils.TokenInfo"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Check server health",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "service.DexPairInfo": {
            "type": "object",
            "properties": {
                "dex_slug": {
                    "type": "string"
                },
                "last_updated": {
                    "type": "string"
                },
                "liquidity": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "network_slug": {
                    "type": "string"
                },
                "percent_change_price_1h": {
                    "type": "number"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "service.NFTFloorPriceInfo": {
            "type": "object",
            "properties": {
                "collection_slug": {
                    "type": "string"
                },
                "floor_price": {
                    "type": "number"
                },
                "floor_price_symbol": {
                    "type": "string"
                },
                "floor_price_usd": {
                    "type": "number"
                }
            }
        },
        "utils.TokenInfo": {
            "type": "object",
            "properties": {
                "lastUpdated": {
                    "type": "string"
                },
                "percentChange1h": {
                    "type": "number",
                    "format": "float64"
                },
                "percentChange24h": {
                    "type": "number",
                    "format": "float64"
                },
                "price": {
                    "type": "number",
                    "format": "float64"
                },
                "symbol": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Crypto Monitoring API",
	Description:      "This is a crypto monitoring server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
